services:
  - type: web
    name: myportfolio
    runtime: go
    repo: https://github.com/Tynashe271/myportfolio
    plan: free
    region: oregon
    buildCommand: "go build -o portfolio-server ."
    startCommand: "./portfolio-server"
